################################################################################
#+
#  Module:	$KSSDIR/mosfire/gui/Makefile
#
#  Revisions:   
#
#  Author:	Jason Weiss
#
#  Date:	2006/06/28
#
#  Description:	GUI level Makefile for MOSFIRE
#-
################################################################################

#  Include files.

INCLUDE	= 

#  C source and object files.
CFLAGS  = 

SOURCE	= 
OBJECT	= 

DIRS	= 

#  Files to make are ...
FILES	= lighton.png \
	  lightoff.png \
	  target.gif

#  Files to release are ...
RELFILES  = 

#override SYSNAM = kss/mosfire/gui/
#override VERNUM = 1.0.1

#  Include general make rules (use /etc if no environment variable).

include $(KROOT)/etc/config.mk


all:
install:
	$(CP) $(FILES) ${KROOT}/kss/mosfire/gui/classes/edu/ucla/astro/irlab/util/images/

clean:
