################################################################################
#+
#  Module:	$KSSDIR/mosfire/gui/lib/Makefile
#
#  Revisions:   
#
#  Author:	Jason Weiss
#
#  Date:	2007/07/09
#
#  Description:	Makefile for MOSFIRE external libraries
#-
################################################################################

#  Include files.

INCLUDE	= 

#  C source and object files.
CFLAGS  = 

SOURCE	= 
OBJECT	= 

DIRS	= 

#  Files to make are ...
FILES	= 

#  Files to release are ...
RELFILES = fits.jar \
	   jdom.jar \
	   jcommon.jar \
	   jfreechart.jar \
	   log4j.jar

RELDAT 	 = 

override SYSNAM = kss/mosfire/gui/lib/
override VERNUM = 1.0.1

#  Include general make rules (use /etc if no environment variable).

include $(KROOT)/etc/config.mk

